[profile.default]
src = "src"
test = "test"
solc = "0.8.26"
optimizer = true
optimizer_runs = 200
optimizer_details = { constantOptimizer = false }
via_ir = true
evm_version = "cancun"
bytecode_hash = "none"

[profile.default.fuzz]
runs = 256
